# fly.toml app configuration file for imc-ep

app = 'imc-ep'
primary_region = 'gru'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

# [NUEVA SECCIÓN AÑADIDA]
# Esto le dice a Fly.io que cree un disco persistente llamado "simcep_data"
# y lo haga accesible dentro de nuestra aplicación en la carpeta /data
[mounts]
  source = "simcep_data"
  destination = "/data"