# fly.toml app configuration file for imc-ep

app = 'imc-ep'
primary_region = 'gru'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  # *** ESTO DEBE SER UNA TABLA DE ARRAY: [[http_service.checks]] ***
  # La clave 'checks' ahora es un array de objetos HTTPCheck
  [[http_service.checks]] 
    # Nombre del chequeo (puede ser cualquiera)
    grace_period = "5s"
    interval = "15s"
    method = "GET"
    # La ruta '/status' es la que añadimos a server.js y devuelve 200 OK
    path = "/status" 
    timeout = "5s"
  # *** FIN CORRECCIÓN ***

[mounts]
  source = "simcep_data"
  destination = "/data"